Hm/e1 us2 ts2 transaction api
ucr-if7100/transaction-service pull request #2
Opened 2023-06-03 23:43 UTC by henrymc03

Creacion del servicio de transaccion para realizar un ingreso o un gasto

2023-06-09 00:41 UTC, leocamachocr requested changes

2023-06-09 00:41 UTC, leocamachocr commented on transaction-service/src/main/java/ucr/gasIn/transactionservice/controller/TransactionController.java
> +    public ResponseEntity<Transaction> get(@PathVariable Integer id) {
Crear entidades separadas para la comunicación con rest

2023-06-09 00:41 UTC, leocamachocr commented on transaction-service/src/main/java/ucr/gasIn/transactionservice/domain/Category.java
> +    private int id;
cambiar a UUID

2023-06-09 00:41 UTC, leocamachocr commented on transaction-service/src/main/java/ucr/gasIn/transactionservice/domain/Transaction.java
> +    public Transaction(int id, int idUser, String numRefBank, String description, char type, float amount,String date, Category idCategory, int idAccount) {
nth: usar builders

2023-06-28 21:10 UTC, Maikel06 approved these changes

2023-06-28 21:15 UTC, Maikel06 reviewed
Hacer cambios del profe

2023-06-28 21:22 UTC, merged